services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "viarticles"
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "123admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - viarticles-data:/var/lib/postgresql/data
    ports:
      - "6800:5432"

volumes:
  viarticles-data: